/**:
  # Constants
  constants:
    max_distance: &max_distance 150.0  # Maximum distance (meters)
    max_height: &max_height 250.0      # Maximum height (meters)

  # ROS Parameters
  ros__parameters:
    # CUDA Stream Settings
    cuda_stream_type: 1  # 0: default, 1: blocking async, 2: non-blocking async, 3: per-thread default

    # Miscellaneous
    voxel_size: 0.75
    num_cameras: 1
    use_tf_transforms: true
    mapping_type: "static_tsdf"  # Options: ["static_tsdf", "static_occupancy"]

    # Processing Frequencies (Hz)
    tick_period_ms: 10  # Processing tick period (ms)
    integrate_depth_rate_hz: 10.0
    integrate_color_rate_hz: 5.0
    integrate_lidar_rate_hz: 10.0
    update_mesh_rate_hz: 5.0
    update_esdf_rate_hz: 10.0
    publish_layer_rate_hz: 5.0
    publish_debug_vis_rate_hz: 2.0
    decay_tsdf_rate_hz: 5.0
    decay_dynamic_occupancy_rate_hz: 10.0
    clear_map_outside_radius_rate_hz: 1.0

    # Logging and Debugging
    print_rates_to_console: false
    print_timings_to_console: false
    print_delays_to_console: false
    print_queue_drops_to_console: false
    print_statistics_on_console_period_ms: 10000

    # ESDF Settings
    esdf_mode: "3d"  # Options: ["2d", "3d"]
    publish_esdf_distance_slice: true

    # Sensor Usage
    use_color: true
    use_depth: true
    use_lidar: true

    # Lidar Settings
    lidar_width: 2048
    lidar_height: 128
    lidar_vertical_fov_rad: 0.785398163  # 45 degrees
    min_angle_below_zero_elevation_rad: -0.392699082  # -22.5 degrees
    max_angle_above_zero_elevation_rad: 0.392699082   # 22.5 degrees
    lidar_min_valid_range_m: 2.5
    lidar_max_valid_range_m: 200.0
    use_non_equal_vertical_fov_lidar_params: false

    # Input Queue
    maximum_input_queue_length: 20

    # Map Clearing Settings
    map_clearing_radius_m: -1.0  # Disable if < 0.0
    map_clearing_frame_id: "base_link"

    # QoS Settings
    input_qos: "SYSTEM_DEFAULT"

    # Visualization
    esdf_slice_bounds_visualization_attachment_frame_id: "base_link"
    esdf_slice_bounds_visualization_side_length: 10.0
    workspace_height_bounds_visualization_attachment_frame_id: "base_link"
    workspace_height_bounds_visualization_side_length: 10.0
    layer_visualization_min_tsdf_weight: 0.01
    layer_visualization_exclusion_height_m: *max_height
    layer_visualization_exclusion_radius_m: *max_distance
    layer_visualization_undo_gamma_correction: false
    max_back_projection_distance: *max_distance
    back_projection_subsampling: 1  # No subsampling if = 1
    layer_streamer_bandwidth_limit_mbps: -1.0  # Unlimited bandwidth

    # Multi-Mapper Settings
    multi_mapper:
      connected_mask_component_size_threshold: 500
      remove_small_connected_components: true

    # Static Mapper Settings
    static_mapper:
      # Lidar Integration
      lidar_projective_integrator_max_integration_distance_m: *max_distance

      # Euclidean Signed Distance Field

      esdf_slice_height: 0.5
      esdf_slice_min_height: 0.5
      esdf_slice_max_height: 5.0
      
      esdf_integrator_min_weight: 0.01
      esdf_integrator_max_site_distance_vox: 5.0
      esdf_integrator_max_distance_m: *max_distance

      # Depth Preprocessing
      do_depth_preprocessing: false
      depth_preprocessing_num_dilations: 3

      # Projective Integrator (TSDF/Color/Occupancy)
      projective_integrator_max_integration_distance_m: *max_distance
      projective_integrator_truncation_distance_vox: 6.0
      projective_integrator_weighting_mode: "inverse_square_tsdf_distance_penalty"
      projective_integrator_max_weight: 5.0
      projective_tsdf_integrator_invalid_depth_decay_factor: -1.0

      # Occupancy Integration
      free_region_decay_probability: 0.8
      free_region_occupancy_probability: 0.2
      occupied_region_decay_probability: 0.05
      occupied_region_occupancy_probability: 0.95
      unobserved_region_occupancy_probability: 0.5
      occupied_region_half_width_m: 5.0

      # View Calculator
      raycast_subsampling_factor: 2
      workspace_bounds_type: "height_bounds"  # Options: ["unbounded", "height_bounds", "bounding_box"]
      workspace_bounds_min_corner_x_m: 0.0
      workspace_bounds_min_corner_y_m: 0.0
      workspace_bounds_min_height_m: 50.0
      workspace_bounds_max_corner_x_m: 0.0
      workspace_bounds_max_corner_y_m: 0.0
      workspace_bounds_max_height_m: *max_height

      # Mesh Integrator
      mesh_integrator_min_weight: 0.1
      mesh_integrator_weld_vertices: true

      # TSDF Decay Integration
      tsdf_decay_factor: 0.99
      tsdf_decayed_weight_threshold: 0.0001
      exclude_last_view_from_decay: true
      tsdf_set_free_distance_on_decayed: false
      tsdf_decayed_free_distance_vox: 4.0
      decay_integrator_deallocate_decayed_blocks: true

      # Mesh Streamer
      layer_streamer_exclusion_height_m: *max_height
      layer_streamer_exclusion_radius_m: *max_distance